-- field_error
INSERT INTO field_error (id, name) VALUES (1, 'Transacción');
INSERT INTO field_error (id, name) VALUES (2, 'ID del remitente o emisor');
INSERT INTO field_error (id, name) VALUES (3, 'ID Receptor');
INSERT INTO field_error (id, name) VALUES (4, 'Fecha');
INSERT INTO field_error (id, name) VALUES (5, 'Hora');
INSERT INTO field_error (id, name) VALUES (6, 'Correlativo');
INSERT INTO field_error (id, name) VALUES (7, 'Identificación única de transacción');
INSERT INTO field_error (id, name) VALUES (8, 'Finalidad');
INSERT INTO field_error (id, name) VALUES (9, 'Calificador del remitente o emisor');
INSERT INTO field_error (id, name) VALUES (010, 'Tipo de Operación');
INSERT INTO field_error (id, name) VALUES (101, 'CODIGO_PAIS_AFILIADO');
INSERT INTO field_error (id, name) VALUES (102, 'TIPO_DOCUMENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (103, 'NUMERO_DOCUMENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (104, 'NACIONALIDAD_AFILIADO');
INSERT INTO field_error (id, name) VALUES (105, 'AP_PATERNO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (106, 'AP_MATERNO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (107, 'AP_CASADA_AFILIADO');
INSERT INTO field_error (id, name) VALUES (108, 'NOMBRES_AFILIADO');
INSERT INTO field_error (id, name) VALUES (109, 'FECHA_NACIMIENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (110, 'UBIGEO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (111, 'GENERO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (112, 'ESTADO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (113, 'FECHA_FALLECIMIENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (114, 'FECHA_VALIDACION_RENIEC');
INSERT INTO field_error (id, name) VALUES (115, 'CODIGO_PAIS_TUTOR');
INSERT INTO field_error (id, name) VALUES (116, 'TIPO_DOCUMENTO_TUTOR');
INSERT INTO field_error (id, name) VALUES (117, 'NUMERO_DOCUMENTO_TUTOR');
INSERT INTO field_error (id, name) VALUES (118, 'VINCULO_TUTOR');
INSERT INTO field_error (id, name) VALUES (119, 'CODIGO_PAIS_ACTUALIZAR');
INSERT INTO field_error (id, name) VALUES (120, 'TIPO_DOCUMENTO_ACTUALIZAR');
INSERT INTO field_error (id, name) VALUES (121, 'NUMERO_DOCUMENTO_ACTUALIZAR');
INSERT INTO field_error (id, name) VALUES (122, 'FECHA_ACTUALIZACION_AFILIADO');
INSERT INTO field_error (id, name) VALUES (201, 'CODIGO_INTERNO');
INSERT INTO field_error (id, name) VALUES (202, 'CODIGO_CONTRATO');
INSERT INTO field_error (id, name) VALUES (203, 'CODIGO_PRODUCTO');
INSERT INTO field_error (id, name) VALUES (204, 'ESTADO_AFILIACION');
INSERT INTO field_error (id, name) VALUES (205, 'PARENTESCO');
INSERT INTO field_error (id, name) VALUES (206, 'CODIGO_PAIS_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (207, 'TIPO_DOCUMENTO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (208, 'NUMERO_DOCUMENTO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (209, 'CODIGO_UNICO_MULTISECTORIAL');
INSERT INTO field_error (id, name) VALUES (210, 'REGIMEN');
INSERT INTO field_error (id, name) VALUES (211, 'FECHA_ACTUALIZACION_ESTADO');
INSERT INTO field_error (id, name) VALUES (212, 'CAUSAL_BAJA');
INSERT INTO field_error (id, name) VALUES (213, 'TIPO_PLAN_SALUD');
INSERT INTO field_error (id, name) VALUES (214, 'NOMBRE_PRODUCTO');
INSERT INTO field_error (id, name) VALUES (215, 'FECHA_INICIO_AFILIACION');
INSERT INTO field_error (id, name) VALUES (216, 'FECHA_FIN_AFILIACION');
INSERT INTO field_error (id, name) VALUES (217, 'FECHA_INICIO_COBERTURA');
INSERT INTO field_error (id, name) VALUES (218, 'FECHA_FIN_COBERTURA');
INSERT INTO field_error (id, name) VALUES (219, 'TIPO_COBERTURA');
INSERT INTO field_error (id, name) VALUES (220, 'ADSCRIPCION_RENIPRESS');
INSERT INTO field_error (id, name) VALUES (221, 'CODIGO_PAIS_TITULAR');
INSERT INTO field_error (id, name) VALUES (222, 'TIPO_DOCUMENTO_TITULAR');
INSERT INTO field_error (id, name) VALUES (223, 'NUMERO_DOCUMENTO_TITULAR');
INSERT INTO field_error (id, name) VALUES (224, 'FECHA_NACIMIENTO_TITULAR');
INSERT INTO field_error (id, name) VALUES (225, 'TIPO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (226, 'NOMBRE_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (227, 'AP_PATERNO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (228, 'AP_MATERNO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (229, 'AP_CASADA_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (230, 'FECHA_NACIMIENTO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (231, 'FECHA_ACTUALIZACION');
INSERT INTO field_error (id, name) VALUES (232, 'HORA_ACTUALIZACION');
INSERT INTO field_error (id, name) VALUES (100, 'Representa la combinación de campos que identifica la clave unica de la persona afiliada');
INSERT INTO field_error (id, name) VALUES (200, 'Representa la combinación de campos que identifica la clave unica de cada afiliación que cuenta un afiliado');
INSERT INTO field_error (id, name) VALUES (300, 'Representa la combinación de campos que identifica la identificación del tutor');
INSERT INTO field_error (id, name) VALUES (400, 'Representa la combinación de campos que identifica la identificacion del afiliado a actualizar');
INSERT INTO field_error (id, name) VALUES (600, 'Representa la combinación de campos que identifica la identificacion del titular');
INSERT INTO field_error (id, name) VALUES (700, 'Representa la combinación de campos que identifica la Fecha de validación con Reniec con Fecha de actualización');
INSERT INTO field_error (id, name) VALUES (800, 'Representa la combinación de campos que identifica la Fecha de inicio de Afiliación con Fecha de fin de Afiliación');
INSERT INTO field_error (id, name) VALUES (900, 'Representa la combinación de campos que identifica la Fecha de inicio de Latencia con Fecha de fin de Latencia');

-- field_error_rule
INSERT INTO field_error_rule (id, description) values(0, 'Error general no especificado');
INSERT INTO field_error_rule (id, description) values(1, 'Validar que el campo sea requerido');
INSERT INTO field_error_rule (id, description) values(2, 'Validar el tamaño  definido del campo');
INSERT INTO field_error_rule (id, description) values(3, 'Validar el tipo definido del campo.');
INSERT INTO field_error_rule (id, description) values(4, 'Validar que el código de País guarde relacion con el tipo de documento');
INSERT INTO field_error_rule (id, description) values(5, 'Validar que el tamaño del número de documento sea la que corresponda');
INSERT INTO field_error_rule (id, description) values(6, 'El Apellido Paterno del afiliado es requerido siempre en cuando los campos del  apellido paterno y materno también son vacíos.');
INSERT INTO field_error_rule (id, description) values(7, 'Validar la fecha en un rango de 1900 hasta 2050');
INSERT INTO field_error_rule (id, description) values(8, 'Validar la hora HHMMSS ');
INSERT INTO field_error_rule (id, description) values(9, 'Valida que el datos existe en la tabla maestra de paises');
INSERT INTO field_error_rule (id, description) values(10, 'Valida que el datos existe en la tabla maestra de tipos de documentos');
INSERT INTO field_error_rule (id, description) values(11, 'Valida la identidad de la persona ');
INSERT INTO field_error_rule (id, description) values(12, 'Valida que el datos existe en la tabla maestra de ubigeos');
INSERT INTO field_error_rule (id, description) values(13, 'Valida que el datos existe en la tabla maestra de generos');
INSERT INTO field_error_rule (id, description) values(14, 'Valida que el datos existe en la tabla maestra de códigos de indicador de fallecido');
INSERT INTO field_error_rule (id, description) values(15, 'Valida que el datos existe en la tabla maestra de códigos de régimen del afiliado');
INSERT INTO field_error_rule (id, description) values(16, 'Valida que el datos existe en la tabla maestra de códigos de estados del afiliado');
INSERT INTO field_error_rule (id, description) values(17, 'Valida que el datos existe en la tabla maestra de códigos de causales de baja');
INSERT INTO field_error_rule (id, description) values(18, 'Valida que el datos existe en la tabla maestra de códigos de plan de salud peas');
INSERT INTO field_error_rule (id, description) values(19, 'Valida que el datos existe en la tabla maestra de códigos interno del producto');
INSERT INTO field_error_rule (id, description) values(20, 'Valida que el datos existe en la tabla maestra de códigos interno de la cobertura');
INSERT INTO field_error_rule (id, description) values(21, 'Valida que el datos existe en la tabla maestra de códigos del parentesco de afiliado');
INSERT INTO field_error_rule (id, description) values(22, 'Valida que el datos existe en la tabla maestra de códigos del Renipress del afiliado');
INSERT INTO field_error_rule (id, description) values(23, 'Valida que el datos existe en la tabla maestra de códigos del tipos de contratante ');
INSERT INTO field_error_rule (id, description) values(24, 'Valida datallada de datos personales del afiiado con la Reniec');
INSERT INTO field_error_rule (id, description) values(25, 'Valida persona fallecida con la Reniec');
INSERT INTO field_error_rule (id, description) values(26, 'Valida clave de persona a actualizar exista en el padron de afiliados');
INSERT INTO field_error_rule (id, description) values(27, 'Valida que exista el titular de un afiliación familiar');
INSERT INTO field_error_rule (id, description) values(28, 'Valida de fechas inicio y fin de afiliación e inicio y fin de cobertura');
INSERT INTO field_error_rule (id, description) values(29, 'Valida la clave de la identificación de una afiliación dependiendo de la operación');
INSERT INTO field_error_rule (id, description) values(30, 'Validar régimen por IAFAS');
INSERT INTO field_error_rule (id, description) values(31, 'Validar plan de salud por IAFAS');
INSERT INTO field_error_rule (id, description) values(32, 'Evaluar el campo estado de alta');
INSERT INTO field_error_rule (id, description) values(33, 'Evaluar el campo estado de actualizacion');
INSERT INTO field_error_rule (id, description) values(34, 'Evaluar el campo estado de baja');
INSERT INTO field_error_rule (id, description) values(35, 'Verifica la IAFAS');
INSERT INTO field_error_rule (id, description) values(36, 'Valida que no existe el Código Multiserctorial');
INSERT INTO field_error_rule (id, description) values(37, 'Evaluar el estado de baja de una persona fallecida');
INSERT INTO field_error_rule (id, description) values(38, 'Valida si la IAFAS esta permitido transaccional via online ');
INSERT INTO field_error_rule (id, description) values(39, 'Valida que se envie 0 ó 1, referencia ID(29) de especificaciones técnicas');
INSERT INTO field_error_rule (id, description) values(40, 'Valida que se envie 0 ó 1, referencia ID(71) de especificaciones técnicas');
INSERT INTO field_error_rule (id, description) values(41, 'Valida que el Afiliado no cuente con derechohabientes activos');
INSERT INTO field_error_rule (id, description) values(42, 'Valida que el Afiliado no cuente con otras afiliaciónes activas');
INSERT INTO field_error_rule (id, description) values(43, 'Valida que la Fecha de Validación con Reniec sea anterior a la Fecha de Proceso(Actualización)');
INSERT INTO field_error_rule (id, description) values(44, 'Valida que los datos del Titular correspondan al Parentesco');

-- lib_error
INSERT INTO lib_error (id, description) VALUES (0, 'Operación correcta');
INSERT INTO lib_error (id, description) VALUES (101, 'Tipo operación nulo/vacio/no existe');
INSERT INTO lib_error (id, description) VALUES (11, 'Nombre transaccion nulo');
INSERT INTO lib_error (id, description) VALUES (21, 'Código de remitente nulo');
INSERT INTO lib_error (id, description) VALUES (31, 'Código de receptor nulo');
INSERT INTO lib_error (id, description) VALUES (41, 'Fecha de transaccion nulo');
INSERT INTO lib_error (id, description) VALUES (51, 'Hora de transaccion nulo');
INSERT INTO lib_error (id, description) VALUES (61, 'Correlativo generado por el emisor de transaccion nulo');
INSERT INTO lib_error (id, description) VALUES (71, 'Código de identificacion unica de transaccion nulo');
INSERT INTO lib_error (id, description) VALUES (81, 'Codigo tipo de finalidad de transaccion nulo');
INSERT INTO lib_error (id, description) VALUES (91, 'Tipo de calificador del remitente nulo');
INSERT INTO lib_error (id, description) VALUES (1081, 'no se encontro afiliado / nombre del afiliado nulo o vacio');
INSERT INTO lib_error (id, description) VALUES (1056, 'El Apellido Paterno del afiliado es requerido siempre y cuando los campos apellido materno y de casada son vacíos');
INSERT INTO lib_error (id, description) VALUES (1061, 'campo ApMaternoAfiliado nulo o vacio');
INSERT INTO lib_error (id, description) VALUES (1021, 'campo TiDocumentoAfil nulo o vacio');
INSERT INTO lib_error (id, description) VALUES (1031, 'campo NuDocumentoAfil vacío o nulo');
INSERT INTO lib_error (id, description) VALUES (1121, 'EstadoAfiliado vacío o nulo');
INSERT INTO lib_error (id, description) VALUES (1091, 'FeNacimiento null o vacío');
INSERT INTO lib_error (id, description) VALUES (1111, 'Genero null o vacío');
INSERT INTO lib_error (id, description) VALUES (1011, 'CoPaisDoc null o vacío');
INSERT INTO lib_error (id, description) VALUES (1161, 'TiDocTutor null o vacío');
INSERT INTO lib_error (id, description) VALUES (1171, 'NuDocTutor null o vacío');
INSERT INTO lib_error (id, description) VALUES (1181, 'VinculoTutor null o vacío');
INSERT INTO lib_error (id, description) VALUES (1151, 'CoPaisEmisorDocTutor null o vacío');
INSERT INTO lib_error (id, description) VALUES (2221, 'TiDocTitular null o vacío');
INSERT INTO lib_error (id, description) VALUES (2231, 'NuDocTitular null o vacío');
INSERT INTO lib_error (id, description) VALUES (2241, 'FeNacimientoTitular null o vacío');
INSERT INTO lib_error (id, description) VALUES (2211, 'CoPaisEmisorDocTitular null o vacío');
INSERT INTO lib_error (id, description) VALUES (2251, 'TiContratante null o vacío');
INSERT INTO lib_error (id, description) VALUES (2071, 'TiDocContratante null o vacío');
INSERT INTO lib_error (id, description) VALUES (2081, 'NuDocContratante null o vacío');
INSERT INTO lib_error (id, description) VALUES (2061, 'CoPaisEmisorDocContratante   null o vacío');
INSERT INTO lib_error (id, description) VALUES (2011, 'CoAfiliacion null o vacío');
INSERT INTO lib_error (id, description) VALUES (2021, 'CoContrato null o vacío');
INSERT INTO lib_error (id, description) VALUES (2101, 'Tiregimen null o vacío');
INSERT INTO lib_error (id, description) VALUES (2041, 'EsAfiliacion null o vacío');
INSERT INTO lib_error (id, description) VALUES (2131, 'TiPlanSalud null o vacío');
INSERT INTO lib_error (id, description) VALUES (2141, 'NoProductoSalud null o vacío');
INSERT INTO lib_error (id, description) VALUES (2031, 'CoProducto null o vacío');
INSERT INTO lib_error (id, description) VALUES (2051, 'Parentesco null o vacío');
INSERT INTO lib_error (id, description) VALUES (1001, 'PkAfiliado null o vacío');
INSERT INTO lib_error (id, description) VALUES (2151, 'FeIniAfiliacion null o vacío');
INSERT INTO lib_error (id, description) VALUES (12, 'Caracteres ingresados en nombre transaccion');
INSERT INTO lib_error (id, description) VALUES (22, 'Caracteres ingresados en codigo remitente');
INSERT INTO lib_error (id, description) VALUES (32, 'Caracteres ingresados en codigo receptor');
INSERT INTO lib_error (id, description) VALUES (42, 'Caracteres ingresados en Fecha de transaccion');
INSERT INTO lib_error (id, description) VALUES (52, 'Caracteres ingresados en Hora de transaccion');
INSERT INTO lib_error (id, description) VALUES (62, 'Caracteres ingresados en Correlativo emisor de transaccion');
INSERT INTO lib_error (id, description) VALUES (72, 'Caracteres ingresados en Código de identificacion unica de transaccion');
INSERT INTO lib_error (id, description) VALUES (82, 'Caracteres ingresados en Código tipo de finalidad de transaccion');
INSERT INTO lib_error (id, description) VALUES (92, 'Caracteres ingresados en Tipo de calificador del remitente');
INSERT INTO lib_error (id, description) VALUES (102, 'TiOperacion tamaño no es 2');
INSERT INTO lib_error (id, description) VALUES (1082, 'NoAfiliado1 tamaño no esta entre 1 y 35 / NoAfiliado2 tamaño es mayor que 25 / NoAfiliado mayor a 60');
INSERT INTO lib_error (id, description) VALUES (1062, 'ApMaternoAfiliado tamaño mayor a 50');
INSERT INTO lib_error (id, description) VALUES (1022, 'TiDocumentoAfil tamaño  diferente de 1');
INSERT INTO lib_error (id, description) VALUES (1032, 'NuDocumentoAfil tamaño no esta entre 1 y 15');
INSERT INTO lib_error (id, description) VALUES (1122, 'EstadoAfiliado tamaño diferente de 1');
INSERT INTO lib_error (id, description) VALUES (1202, 'TiDocumentoAct tamaño mayor a 1');
INSERT INTO lib_error (id, description) VALUES (1212, 'NuDocumentoAct tamaño mayor a 15');
INSERT INTO lib_error (id, description) VALUES (1072, 'ApCasadaAfiliado mayor a 50');
INSERT INTO lib_error (id, description) VALUES (1042, 'CoNacionalidad tamaño no esta entre 2 y 3');
INSERT INTO lib_error (id, description) VALUES (1102, 'Ubigeo tamaño no esta entre 0 y 12');
INSERT INTO lib_error (id, description) VALUES (1092, 'FeNacimiento tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (1112, 'Genero tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (1012, 'CoPaisDoc tamaño no es 3');
INSERT INTO lib_error (id, description) VALUES (1132, 'Fefallecimiento tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (1192, 'CoPaisEmisorDocAct tamaño mayor a 3');
INSERT INTO lib_error (id, description) VALUES (1222, 'FeActPersonaxIafas tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (1162, 'TiDocTutor tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (1172, 'NuDocTutor tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (1182, 'TiVinculoTutor tamaño mayor que 2');
INSERT INTO lib_error (id, description) VALUES (1142, 'FeValidacionReniec tamaño diferente de 8');
INSERT INTO lib_error (id, description) VALUES (1152, 'CoPaisEmisorDocTutor tamaño diferente de 3');
INSERT INTO lib_error (id, description) VALUES (2222, 'TiDocTitular tamaño diferente de 1');
INSERT INTO lib_error (id, description) VALUES (2232, 'NuDocTitular tamaño no esta entre 1 y 15');
INSERT INTO lib_error (id, description) VALUES (2242, 'FeNacimientoTitular tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2212, 'CoPaisEmisorDocTitular tamaño no es 3');
INSERT INTO lib_error (id, description) VALUES (2252, 'TiContratante tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (2272, 'ApPaternoContratante tamaño mayor de 50');
INSERT INTO lib_error (id, description) VALUES (2262, 'NoContratante1 tamaño mayor a 35 / NoContratante2 tamaño mayor a 25 / NoContratante3 tamaño mayor a 10 / NoContratante4 tamaño mayor a 10 / NoContratante tamaño mayor a 80');
INSERT INTO lib_error (id, description) VALUES (2282, 'ApMaternoContratante tamaño mayor a 50');
INSERT INTO lib_error (id, description) VALUES (2072, 'TiDocContratante tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (2082, 'NuDocContratante tamaño no esta entre 1 y 50');
INSERT INTO lib_error (id, description) VALUES (2292, 'ApCasadaContratante tamaño mayor de 50');
INSERT INTO lib_error (id, description) VALUES (2302, 'FeNacimientoContratante tamaño mayor de 50');
INSERT INTO lib_error (id, description) VALUES (2062, 'CoPaisEmisorDocContratante tamaño no es 3');
INSERT INTO lib_error (id, description) VALUES (2012, 'CoAfiliacio tamaño mayor a 20');
INSERT INTO lib_error (id, description) VALUES (2022, 'CoContrato tamaño mayor a 30');
INSERT INTO lib_error (id, description) VALUES (2092, 'CoUnicoMultisectorial tamaño 0 o mayor a 20');
INSERT INTO lib_error (id, description) VALUES (2102, 'Tiregimen tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (2042, 'EsAfiliacion tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (2122, 'CoCausalBaja tamaño 0 o mayor a 20');
INSERT INTO lib_error (id, description) VALUES (2132, 'TiPlanSalud tamaño no es 1');
INSERT INTO lib_error (id, description) VALUES (2142, 'NoProductoSalud tamaño menor de 1 o mayor de 50');
INSERT INTO lib_error (id, description) VALUES (2032, 'CoProducto tamaño menor de 1 o mayor de 50');
INSERT INTO lib_error (id, description) VALUES (2052, 'Parentesco menor de 1 o mayor de 2');
INSERT INTO lib_error (id, description) VALUES (2202, 'CoRenipress tamaño 0 o mayor que 10');
INSERT INTO lib_error (id, description) VALUES (1002, 'PkAfiliado tamaño no esta entre 12 y 19');
INSERT INTO lib_error (id, description) VALUES (2112, 'FeActEstado tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2152, 'FeIniAfiliacion tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2162, 'FeFinAfiliacion tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2172, 'FeIniCobertura tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2182, 'FeFinCobertura tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2312, 'FeActOperacion tamaño no es 8');
INSERT INTO lib_error (id, description) VALUES (2322, 'TiActOperacion tamaño 0 o mayor de 6');
INSERT INTO lib_error (id, description) VALUES (2192, 'TiCobertura tamaño 0 o mayor de 1');
INSERT INTO lib_error (id, description) VALUES (13, 'Caracteres ingresados en nombre transaccion');
INSERT INTO lib_error (id, description) VALUES (23, 'Caracteres ingresados en codigo remitente');
INSERT INTO lib_error (id, description) VALUES (33, 'Caracteres ingresados en codigo receptor');
INSERT INTO lib_error (id, description) VALUES (43, 'Caracteres ingresados en Fecha de transaccion');
INSERT INTO lib_error (id, description) VALUES (53, 'Caracteres ingresados en Hora de transaccion');
INSERT INTO lib_error (id, description) VALUES (63, 'Caracteres ingresados en Correlativo emisor de transaccion');
INSERT INTO lib_error (id, description) VALUES (73, 'Caracteres ingresados en Codigo de identificacion unica de transaccion');
INSERT INTO lib_error (id, description) VALUES (83, 'Caracteres ingresados en Codigo tipo de finalidad de transaccion');
INSERT INTO lib_error (id, description) VALUES (93, 'Caracteres ingresados en Tipo de calificador del remitente');
INSERT INTO lib_error (id, description) VALUES (103, 'TiOperacion error Alfanumerico');
INSERT INTO lib_error (id, description) VALUES (1053, 'ApPaternoAfiliado tamaño nulo o vacío o caracter no permitido');
INSERT INTO lib_error (id, description) VALUES (1083, 'NoAfiliado1 caracter no permitido / NoAfiliado2 caracter no permitido');
INSERT INTO lib_error (id, description) VALUES (1063, 'ApMaternoAfiliado caracter no permitido');
INSERT INTO lib_error (id, description) VALUES (1023, 'TiDocumentoAfil no es dígito');
INSERT INTO lib_error (id, description) VALUES (1033, 'NuDocumentoAfil alfanumérico');
INSERT INTO lib_error (id, description) VALUES (1123, 'EstadoAfiliado no es dígito');
INSERT INTO lib_error (id, description) VALUES (1203, 'TiDocumentoAct no es dígito');
INSERT INTO lib_error (id, description) VALUES (1213, 'NuDocumentoAct error Alfanumerico');
INSERT INTO lib_error (id, description) VALUES (1073, 'ApCasadaAfiliado caracter no válido');
INSERT INTO lib_error (id, description) VALUES (1043, 'CoNacionalidad caracter no válido');
INSERT INTO lib_error (id, description) VALUES (1103, 'Ubigeo no es dígito');
INSERT INTO lib_error (id, description) VALUES (1093, 'FeNacimiento inválida');
INSERT INTO lib_error (id, description) VALUES (1113, 'Genero no es dígito');
INSERT INTO lib_error (id, description) VALUES (1013, 'CoPaisDoc validaCaracterPalabra');
INSERT INTO lib_error (id, description) VALUES (1133, 'Fefallecimiento no válida');
INSERT INTO lib_error (id, description) VALUES (1193, 'CoPaisEmisorDocAct no válida');
INSERT INTO lib_error (id, description) VALUES (1223, 'FeActPersonaxIafas no válida');
INSERT INTO lib_error (id, description) VALUES (1163, 'TiDocTutor no es dígito');
INSERT INTO lib_error (id, description) VALUES (1173, 'NuDocTutor error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (1183, 'TiVinculoTutor no es dígito');
INSERT INTO lib_error (id, description) VALUES (1143, 'FeValidacionReniec inválida');
INSERT INTO lib_error (id, description) VALUES (1153, 'CoPaisEmisorDocTutor no válido');
INSERT INTO lib_error (id, description) VALUES (2223, 'TiDocTitular no es dígito');
INSERT INTO lib_error (id, description) VALUES (2233, 'NuDocTitular error Alfanumerico');
INSERT INTO lib_error (id, description) VALUES (2243, 'FeNacimientoTitular inválida');
INSERT INTO lib_error (id, description) VALUES (2213, 'CoPaisEmisorDocTitular error validaCaracterPalabra');
INSERT INTO lib_error (id, description) VALUES (2253, 'TiContratante no es dígito');
INSERT INTO lib_error (id, description) VALUES (2273, 'ApPaternoContratante caracter inválido');
INSERT INTO lib_error (id, description) VALUES (2263, 'NoContratante1 caracter inválido / NoContratante2 caracter inválido / NoContratante3 caracter inválido / NoContratante4 caracter inválido');
INSERT INTO lib_error (id, description) VALUES (2283, 'ApMaternoContratante caracter inválido');
INSERT INTO lib_error (id, description) VALUES (2073, 'TiDocContratante no es dígito');
INSERT INTO lib_error (id, description) VALUES (2083, 'NuDocContratante error Alfanumerico');
INSERT INTO lib_error (id, description) VALUES (2293, 'ApCasadaContratante caracter inválido');
INSERT INTO lib_error (id, description) VALUES (2303, 'FeNacimientoContratante inválido');
INSERT INTO lib_error (id, description) VALUES (2063, 'CoPaisEmisorDocContratante error validaCaracterPalabra');
INSERT INTO lib_error (id, description) VALUES (2013, 'CoAfiliacion error AlfanumericoGuion');
INSERT INTO lib_error (id, description) VALUES (2023, 'CoContrato error AlfanumericoGuion');
INSERT INTO lib_error (id, description) VALUES (2093, 'CoUnicoMultisectorial error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (2103, 'Tiregimen error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (2043, 'EsAfiliacion error validaSoloDigito');
INSERT INTO lib_error (id, description) VALUES (2123, 'CoCausalBaja error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (2133, 'TiPlanSalud no es dígito');
INSERT INTO lib_error (id, description) VALUES (2143, 'NoProductoSalud caracter inválido');
INSERT INTO lib_error (id, description) VALUES (2033, 'CoProducto error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (2053, 'Parentesco no es dígito');
INSERT INTO lib_error (id, description) VALUES (2203, 'CoRenipress error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (1003, 'PkAfiliado error validaAlfanumerico');
INSERT INTO lib_error (id, description) VALUES (2113, 'FeActEstado inválido');
INSERT INTO lib_error (id, description) VALUES (2153, 'FeIniAfiliacion inválido');
INSERT INTO lib_error (id, description) VALUES (2163, 'FeFinAfiliacion inválido');
INSERT INTO lib_error (id, description) VALUES (2173, 'FeIniCobertura inválido');
INSERT INTO lib_error (id, description) VALUES (2183, 'FeFinCobertura inválido');
INSERT INTO lib_error (id, description) VALUES (2313, 'FeActOperacion inválido');
INSERT INTO lib_error (id, description) VALUES (2323, 'TiActOperacion no es dígito');
INSERT INTO lib_error (id, description) VALUES (2193, 'CoTiCobertura no es dígito');
INSERT INTO lib_error (id, description) VALUES (1024, 'TiDocumentoAfil no corresponde con CoPaisDoc');
INSERT INTO lib_error (id, description) VALUES (1164, 'TiDocTutor no corresponde con TiDocumentoAfil 7 /  TiDocumentoAfil es 7 y CoPaisEmisorDocTutor no es PER y TiDocTutor no es 3 o 4');
INSERT INTO lib_error (id, description) VALUES (2224, 'TiDocTitular no se corresponde con CoPaisEmisorDocTitular es PER');
INSERT INTO lib_error (id, description) VALUES (2074, 'TiDocContratante no se corresponde con CoPaisEmisorDocContratante PER / CoPaisEmisorDocContratante no es PER');
INSERT INTO lib_error (id, description) VALUES (1035, 'NuDocumentoAfil tamaño no es 8 / NuDocumentoAfil tamaño no es 11');
INSERT INTO lib_error (id, description) VALUES (1175, 'NuDocTutor tamaño no es 8 / NuDocTutor tamaño no es 11');
INSERT INTO lib_error (id, description) VALUES (39, 'IdAfiliadoNombre no es 0 o 1');
INSERT INTO lib_error (id, description) VALUES (2235, 'NuDocTitular tamaño no es 8 / NuDocTitular tamaño no es 11');
INSERT INTO lib_error (id, description) VALUES (2085, 'NuDocContratante tamaño no es 8 / NuDocContratante tamaño no es 11');
INSERT INTO lib_error (id, description) VALUES (40, 'IdAfiliacionNombre no es 0 o 1');
INSERT INTO lib_error (id, description) VALUES (80028, 'Fecha de inicio de afiliacion no sea mayor a la fecha de fin de afiliacion');
INSERT INTO lib_error (id, description) VALUES (90028, 'Fecha de inicio de latencia no sea mayor a la fecha de fin de latencia');
INSERT INTO lib_error (id, description) VALUES (70043, 'Fecha de validacion Reniec no sea mayor a fecha de actualizacion');
INSERT INTO lib_error (id, description) VALUES (2121, 'se refiere a que el campo causal de baja no debe estar vacío');
INSERT INTO lib_error (id, description) VALUES (2161, 'se refiere a que la fecha de fin de afiliación vacío o nulo');
INSERT INTO lib_error (id, description) VALUES (1221, 'FFECHA_ACTUALIZACION_AFILIADO es nulo o vacío');
INSERT INTO lib_error (id, description) VALUES (2321, 'campo TiActOperacion(Hora minutos y segundos de Actualización) es nulo o vacío.');
