version: "3.7"

services:

  regafi-proxy:
    image: vicozizou/regafi-proxy:latest
    environment:
      SEMEFA_APP: regafi-proxy
      SERVER_PORT: 9000
      ACTUATOR_PORT: 9001
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      MQ_QUEUE_MANAGER:
      MQ_QUEUE_IN:
      MQ_QUEUE_OUT:
      MQ_CHANNEL:
      MQ_HOSTNAME:
      MQ_PORT:
      JWT_SECRET:
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${ACTUATOR_PORT}:${ACTUATOR_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
