version: "3.7"

volumes:
  logs:

services:
  regafi-proxy:
    image: vicozizou/regafi-proxy:latest
    environment:
      SEMEFA_APP: regafi-proxy
      SERVER_PORT:
      ACTUATOR_PORT:
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      MQ_QUEUE_MANAGER:
      MQ_QUEUE_IN:
      MQ_QUEUE_OUT:
      MQ_CHANNEL:
      MQ_HOSTNAME:
      MQ_PORT:
      JWT_SECRET:
      MQ_NUMBER_OF_TRIES:
      MQ_WAIT_AFTER_TRY:
      MQ_WAIT_INTERVAL:
      REGAFI_LOG_LEVEL:
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${ACTUATOR_PORT}:${ACTUATOR_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app/logs
