server:
  port: ${SERVER_PORT:9002}
management:
  server:
    port: ${ACTUATOR_PORT:9003}
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: ${ACTUATOR_CONTEXT_PATH:/actuator}
      exposure:
        include: info,health,prometheus
spring:
  application:
    name: siteds-gateway
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:semefa}
    username: ${DB_USER:semefa}
    password: ${DB_PASSWORD:semefa}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8
siteds:
  sac-url: ${SAC_URL:http://localhost:9999}
  api-key: ${API_KEY}
  dev-mode: ${DEV_MODE}
web:
  security:
    public-urls:
      - /ws-siteds/**
      - /actuator/**
      - /api/public/**
      - /error**
mq:
  queue-manager: ${MQ_QUEUE_MANAGER:QM.999.998.AC}
  queue-in: ${MQ_QUEUE_IN:QL.995.AC.002.2.IN}
  queue-out: ${MQ_QUEUE_OUT:QL.995.AC.002.2.OUT}
  channel: ${MQ_CHANNEL:CH.SUSALUD.IAFAS_LA}
  hostname: ${MQ_HOSTNAME:app3.susalud.gob.pe}
  port: ${MQ_PORT:1430}
date:
  time-zone: ${TIME_ZONE:UTC-5}
jwt:
  issuer: saludaunclic
  expiration-sec: ${JWT_EXPIRATION_SEC:86400}
  clock-skew-sec: ${JWT_CLOCK_SKEW_SEC:300}
  secret: ${JWT_SECRET:changeme}
cxf:
  path: /siteds_ws
logging:
  level:
    com:
      saludaunclic:
        semefa:
          siteds: ${SITEDS_LOG_LEVEL:INFO}
